export default {
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_ERROR: 'ADD_TODO_ERROR',
  ADD_TODO_ASYNC: 'ADD_TODO_ASYNC',
  TODO_REQUEST: 'TODO_REQUEST',
  REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',
  REMOVE_TODO_ERROR: 'REMOVE_TODO_ERROR',
  REMOVE_TODO_ASYNC: 'REMOVE_TODO_ASYNC',
};
